### ISSUE TITLE
Log error during HA shutdown

### ISSUE THREAD

**Issue by chemelli74** [esphome/aioesphomeapi#46]
During shutdown of HA I always get the following log line:

`2021-06-27 18:02:31 INFO (MainThread) [aioesphomeapi.connection] 192.168.xxx.yyy: Error while reading incoming messages: Error while receiving data: 0 bytes read on a total of 1 expected bytes`

Please notice that beside it should not be logged at all, it's has a **Error** description with **INFO** log level.

Simone

**Comment by OttoWinter** [comment]
It's intentionally info log level. Logging it as error just spams the HA logs because unfortunately the ESPs don't always have good WiFi connections and drop off occasionally. Then we receive tons of issues for people that wonder why it appears in their HA error log, even though the device recovered just fine after a reconnect.

**Comment by chemelli74** [comment]
> It's intentionally info log level. Logging it as error just spams the HA logs because unfortunately the ESPs don't always have good WiFi connections and drop off occasionally. Then we receive tons of issues for people that wonder why it appears in their HA error log, even though the device recovered just fine after a reconnect.

Maybe it's the case to slit in two then:

first occurrence it happens just a INFO saying "Retrying dropped connection"
and from the second on, WARNING or ERROR saying "Connection issue"

Simone

**Comment by chemelli74** [comment]
No fix in sight
